# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 651bbe3ba11544e9b4bb0c843ef03ae9af1accb251374686b13766cff7359a49b5718f1c9a6c9b895d78081b1e0b77ad9c8d92ed29c266b0dbed7e6a5d70a8de

test:
  secret_key_base: 9ade2dad6f274ee9bfc5f671bf353914c89591941c7c225f3d5f5976fb41945ce2e50e7e79adec93d54fc23410c8ce04eec9cc0907a8e5d69579e5221f077aab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
